plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.lab1'
    compileSdk 37

    defaultConfig {
        applicationId "com.example.lab1"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
}
